apiVersion: v1
kind: Service
metadata:
  name: "{{ template "neo4j.core.fullname" . }}-2"
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  selector:
    statefulset.kubernetes.io/pod-name: "{{ template "neo4j.core.fullname" . }}-2"
  ports:
  - protocol: TCP
    nodePort: 31002
    port: 7474
    targetPort: 7474
    name: broswer
  - protocol: TCP
    nodePort: 32002
    port: 7687
    targetPort: 7687
    name: bolt