dependencies:
- name: cp-kafka
  version: 0.1.0
  repository: file://./charts/cp-kafka
  condition: cp-kafka.enabled
- name: cp-zookeeper
  version: 0.1.0
  repository: file://./charts/cp-zookeeper
  condition: cp-zookeeper.enabled
- name: cp-schema-registry
  version: 0.1.0
  repository: file://./charts/cp-schema-registry
  condition: cp-schema-registry.enabled
- name: cp-kafka-rest
  version: 0.1.0
  repository: file://./charts/cp-kafka-rest
  condition: cp-kafka-rest.enabled
- name: cp-kafka-connect-artemis
  version: 0.1.0
  repository: file://./charts/cp-kafka-connect-artemis
  condition: cp-kafka-connect-artemis.enabled
- name: cp-kafka-connect-neo4j
  version: 0.1.0
  repository: file://./charts/cp-kafka-connect-neo4j
  condition: cp-kafka-connect-neo4j.enabled
- name: cp-kafka-connect-mongodb
  version: 0.1.0
  repository: file://./charts/cp-kafka-connect-mongodb
  condition: cp-kafka-connect-mongodb.enabled
- name: cp-ksql-server
  version: 0.1.0
  repository: file://./charts/cp-ksql-server
  condition: cp-ksql-server.enabled
- name: cp-control-center
  version: 0.1.0
  repository: file://./charts/cp-control-center
  condition: cp-control-center.enabled
