apiVersion: v1
kind: ConfigMap
metadata:
  name: promenade-cluster
  labels:
    radanalytics.io/kind: SparkCluster
data:
  config: |-
    worker:
      instances: "1"
      memory: "200Gi"
      cpu: 32
    master:
      instances: "1"
      memory: "1Gi"
      cpu: 1
