apiVersion: v1
kind: ConfigMap
metadata:
  name: promenade
  labels:
    radanalytics.io/kind: SparkApplication
data:
  config: |-
    image: quay.io/jkremser/openshift-spark:2.3-latest
    mainApplicationFile: http://172.16.1.36/FastBCTest.jar
    mainClass: unisannio.FastBC_2C_v1_par
    arguments: "k8s://https://172.16.1.36:8443 bolt://neo4j-neo4j-core-0.promenade.svc:7687 neo4j password mongodb://mongodb-replicaset-headless.promenade.svc:27017/ test c_init kafka-cp-kafka-headless.promenade.svc:9092 2018-09-06T09:00:00 900 d w dist 8 0 . 0.01 10000000"
    #sleep: 300 # repeat each 5 minutes
    driver:
      cores: 8
      coreLimit: 8000m
      memory: 5g
    executor:
      instances: 1
      cores: 8
      coreLimit: 8000m
      memory: 40g
