apiVersion: v1
kind: Service
metadata:
  annotations:
   # Make sure DNS is resolvable during initialization.
   service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: {{ include "artemis.fullname" . }}-master-external
  labels:
{{ include "artemis.labels.standard" . | indent 4 }}
    component: artemis-node
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: tcp
    nodePort: {{ .Values.external.tcp }}
    port: 61616
    protocol: TCP
    targetPort: 61616
  - name: http
    nodePort: {{ .Values.external.http }}
    port: 8161
    protocol: TCP
    targetPort: 8161
  - name: mqtt
    nodePort: {{ .Values.external.mqtt }}
    port: 1883
    protocol: TCP
    targetPort: 1883
  selector:
    app: {{ template "artemis.name" . }}
    release: {{ .Release.Name | quote }}
    component: master
  sessionAffinity: None
  type: NodePort