apiVersion: v1
kind: Service
metadata:
  labels:
    app: spark-driver
  name: spark-driver-service
  namespace: promenade
spec:
  clusterIP: 172.30.148.9
  ports:
    - name: 7078-tcp
      port: 7078
      protocol: TCP
  selector:
    pod-name: spark-driver
  sessionAffinity: None
  type: ClusterIP
